name: "Test all"
on:
    [push]
jobs:
  build:
    name: run_tests_all
    runs-on: ubuntu-latest        
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Set up Java
      uses: actions/setup-java@v2.5.0
      with:
        java-version: '1.8'
    - name: Test with Maven
      run: mvn clean test --file ./pom.xml
